#!/bin/bash

if [ -f /etc/apt/sources.list.d/ubports-developers-ubuntu-overlay-dev-vivid.list ]; then
  echo "The dev ppa is alredy added, use qa-update to update"
  exit
fi

# Gimme root
[ $(id -u) -ne 0 ] && exec sudo $0 $@

mount -o rw,remount /
add-apt-repository ppa:ubports-developers/overlay-dev

if ! cat /etc/apt/preferences.d/extra-ppas.pref | grep -q "LP-PPA-ubports-developers-overlay-dev" ; then
  tee -a /etc/apt/preferences.d/extra-ppas.pref > /dev/null << EOL
Package: *
Pin: release o=LP-PPA-ubports-developers-overlay-dev
Pin-Priority: 1011
EOL
fi

apt update
apt dist-upgrade
