#!/bin/bash

# Gimme root
[ $(id -u) -ne 0 ] && exec sudo $0 $@

mount -o rw,remount /

wget -P /usr/bin https://raw.githubusercontent.com/mariogrip/qa-scripts/master/qa-update
wget -P /usr/bin https://raw.githubusercontent.com/mariogrip/qa-scripts/master/qa-add

chmod +x /usr/bin/qa-update
chmod +x /usr/bin/qa-add
