#!/bin/bash

if [ ! -f /etc/apt/sources.list.d/ubports-developers-ubuntu-overlay-dev-vivid.list ]; then
  echo "The dev ppa is not added, nothing to remove."
  exit
fi

# Gimme root
[ $(id -u) -ne 0 ] && exec sudo $0 $@

mount -o rw,remount /

LINE=$(grep -n "Pin: release o=LP-PPA-ubports-developers-overlay-dev" /etc/apt/preferences.d/extra-ppas.pref | grep -Eo '^[^:]+')
LINES="$((LINE - 2)),$((LINE + 1))d"

sed -e "$LINES" /etc/apt/preferences.d/extra-ppas.pref | tee /etc/apt/preferences.d/extra-ppas.pref
rm /etc/apt/sources.list.d/ubports-developers-ubuntu-overlay-dev-vivid.list || true

apt update
apt dist-upgrade
