#!/bin/bash

if [ ! -f /etc/apt/sources.list.d/ubports-developers-ubuntu-overlay-dev-vivid.list ]; then
  echo "The dev ppa is not added, use qa-add to add it"
  exit
fi

# Gimme root
[ $(id -u) -ne 0 ] && exec sudo $0 $@

mount -o rw,remount /

apt update
apt upgrade
