#!/bin/bash
_ubports-qa()
{
    local cur prev
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    case $COMP_CWORD in
	    1) COMPREPLY=( $(compgen -W "$(ubports-qa -h |awk '/   install/,/    update/{print $1}')" -- ${cur}) );;
	    2)  [ ${prev} = "remove" ] && COMPREPLY=( $(compgen -W "$(ubports-qa list)" -- ${cur}) );;
	    *);;
    esac
    case $cur in
	    -*) COMPREPLY=( $(compgen -W "$(_parse_usage $1)" -- ${cur}) );;
    esac

    return 0
}
complete -F _ubports-qa ubports-qa
